//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInfo {
    
    
    [System.SerializableAttribute()]
    public enum DefenceType {
        
        None = 0,
        
        Break = 1,
        
        Time = 2,
    }
    
    [System.SerializableAttribute()]
    public enum EffectType {
        
        None = 0,
        
        Slow = 1,
        
        AttackUp = 2,
    }
    
    [System.SerializableAttribute()]
    public enum EffectTargetType {
        
        Enemy = 0,
        
        User = 1,
        
        Select = 2,
        
        AllCharacter = 3,
        
        None = 4,
    }
}
