//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataInfo {
    
    
    [System.SerializableAttribute()]
    public class ItemDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private int m_Code;
        
        [UnityEngine.SerializeField()]
        private string m_Name;
        
        [UnityEngine.SerializeField()]
        private string m_Description;
        
        [UnityEngine.SerializeField()]
        private int m_HealHP;
        
        [UnityEngine.SerializeField()]
        private int m_HealsHP;
        
        [UnityEngine.SerializeField()]
        private int m_HealMP;
        
        [UnityEngine.SerializeField()]
        private int m_HealsMP;
        
        public int Code {
            get {
                return this.m_Code;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
        }
        
        public string Description {
            get {
                return this.m_Description;
            }
        }
        
        public int HealHP {
            get {
                return this.m_HealHP;
            }
        }
        
        public int HealsHP {
            get {
                return this.m_HealsHP;
            }
        }
        
        public int HealMP {
            get {
                return this.m_HealMP;
            }
        }
        
        public int HealsMP {
            get {
                return this.m_HealsMP;
            }
        }
    }
    
    public class ItemDBDataTable : DefaultDataTable<DataInfo.ItemDBData> {
    }
}
